-- ==========================================
-- Customer Lifetime Value & Cohort Retention Analysis
-- Tools: MySQL + Tableau
-- ==========================================

-- 1. Create a new database for the project
CREATE DATABASE clv_project;
USE clv_project;

-- 2. Create the Orders table
-- This table will store all customer transactions
CREATE TABLE orders (
    order_id INT,
    customer_id INT,
    order_date DATE,
    quantity INT,
    price DECIMAL(10,2),
    region VARCHAR(100)
);

-- 3. Quick sanity check: count the total number of rows in the dataset
SELECT COUNT(*) AS total_orders FROM orders;

-- ==========================================
-- SECTION A: Calculate Customer Lifetime Value (CLV)
-- ==========================================
-- CLV = Total revenue generated by a customer across all orders

SELECT 
    customer_id,
    SUM(quantity * price) AS lifetime_value,       -- Total revenue per customer
    MIN(order_date) AS first_order,                -- First purchase date
    MAX(order_date) AS last_order,                 -- Most recent purchase date
    COUNT(DISTINCT order_id) AS total_orders       -- Number of unique orders
FROM orders
GROUP BY customer_id
ORDER BY lifetime_value DESC;

-- ==========================================
-- SECTION B: Monthly Cohort Retention Analysis
-- ==========================================
-- Step 1: Identify the month of each customer's first order
WITH first_orders AS (
    SELECT 
        customer_id,
        MIN(order_date) AS first_order_date
    FROM orders
    GROUP BY customer_id
),

-- Step 2: Map each order to the customer's cohort month and active month
cohort_activity AS (
    SELECT 
        o.customer_id,
        DATE_FORMAT(f.first_order_date, '%Y-%m') AS cohort_month,  -- First order month
        DATE_FORMAT(o.order_date, '%Y-%m') AS active_month         -- Month of current order
    FROM orders o
    JOIN first_orders f ON o.customer_id = f.customer_id
)

-- Step 3: Count how many unique customers are active each month for each cohort
SELECT 
    cohort_month,
    active_month,
    COUNT(DISTINCT customer_id) AS active_customers
FROM cohort_activity
GROUP BY cohort_month, active_month
ORDER BY cohort_month, active_month;


